### ISSUE TITLE
代理池没法用啊

### ISSUE THREAD

**Issue by fanrui1999** [KongWiki/ProxyPool#1]
redis.exceptions.RedisError: ZADD requires an equal number of values and scores

**Comment by KongWiki** [comment]
redis的版本问题
redis 2.10.x版本的 zadd用法是 zadd(key-name, member, score)
redis 3.0版本的zadd用法是 zadd(key0-name, {member:score})
我使用的是3.0之后的

**Comment by Winniekun** [comment]
> redis.exceptions.RedisError: ZADD requires an equal number of values and scores
redis版本问题:
redis 2.10.x版本的 zadd用法是 zadd(key-name, member, score)
redis 3.0版本的zadd用法是 zadd(key0-name, {member:score})
我用的是3.x
